# site_name: DSA Review


site_name: DSA and ML Wiki
theme:
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Dynamic Programming: dp.md
  - Graphs: graph.md
  - Recursion & Backtracking: rb.md
  - Sliding Window/ Two Pointers: tp.md
  - Sorting and Binary Search: sb.md
  - Bit Manipulation: bm.md
  - Other Topics:
      - Bayesian Statistics: bs.md
      - Classical Statistics: cs.md
      - Machine Learning: ml.md
      